version: "3.3"

services: 

  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    depends_on:
      - mysql
     

  mysql:
    image: mysql
    container_name: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=politute


  apache:
    container_name: apache
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app